# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 800))
        MainWindow.setStyleSheet("background-color:  #FFFFF0;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: #F59100;\n"
"")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setMinimumSize(QtCore.QSize(120, 0))
        self.Btn_Toggle.setStyleSheet("color: #fff;\n"
"border: 0px solid;")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Content)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidgetMain = QtWidgets.QStackedWidget(self.page_1)
        self.stackedWidgetMain.setObjectName("stackedWidgetMain")
        self.trackerPage = QtWidgets.QWidget()
        self.trackerPage.setObjectName("trackerPage")
        self.groupBox = QtWidgets.QGroupBox(self.trackerPage)
        self.groupBox.setGeometry(QtCore.QRect(-20, 20, 1227, 691))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("border: none;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.frameGraphMain = QtWidgets.QFrame(self.groupBox)
        self.frameGraphMain.setGeometry(QtCore.QRect(520, 10, 671, 481))
        self.frameGraphMain.setMinimumSize(QtCore.QSize(300, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frameGraphMain.setPalette(palette)
        self.frameGraphMain.setAutoFillBackground(False)
        self.frameGraphMain.setStyleSheet("border-radius: 20;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.frameGraphMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraphMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraphMain.setObjectName("frameGraphMain")
        self.frameGraphMini = QtWidgets.QFrame(self.groupBox)
        self.frameGraphMini.setGeometry(QtCore.QRect(30, 10, 471, 391))
        self.frameGraphMini.setStyleSheet("border-radius:20;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.frameGraphMini.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraphMini.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraphMini.setObjectName("frameGraphMini")
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setGeometry(QtCore.QRect(40, 540, 241, 151))
        self.frame_4.setStyleSheet("border-radius: 20;\n"
"background-color: #F59100;\n"
"border: 0;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.stopButton1 = QtWidgets.QPushButton(self.frame_4)
        self.stopButton1.setGeometry(QtCore.QRect(50, 90, 93, 28))
        self.stopButton1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10;\n"
"")
        self.stopButton1.setObjectName("stopButton1")
        self.startButton1 = QtWidgets.QPushButton(self.frame_4)
        self.startButton1.setGeometry(QtCore.QRect(50, 90, 93, 28))
        self.startButton1.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"border-radius: 10;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E5E5E5;\n"
"}")
        self.startButton1.setObjectName("startButton1")
        self.comboBoxArd = QtWidgets.QComboBox(self.frame_4)
        self.comboBoxArd.setGeometry(QtCore.QRect(30, 40, 141, 31))
        self.comboBoxArd.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Microsoft YaHei UI\";")
        self.comboBoxArd.setObjectName("comboBoxArd")
        self.refreshButton = QtWidgets.QPushButton(self.frame_4)
        self.refreshButton.setGeometry(QtCore.QRect(180, 40, 31, 28))
        self.refreshButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"border-radius: 10;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E5E5E5;\n"
"}")
        self.refreshButton.setObjectName("refreshButton")
        self.frame_5 = QtWidgets.QFrame(self.groupBox)
        self.frame_5.setGeometry(QtCore.QRect(340, 540, 241, 151))
        self.frame_5.setStyleSheet("border-radius: 20;\n"
"background-color: #F59100;\n"
"border: 0;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_name = QtWidgets.QLabel(self.frame_5)
        self.label_name.setGeometry(QtCore.QRect(0, 40, 241, 20))
        self.label_name.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.label_age = QtWidgets.QLabel(self.frame_5)
        self.label_age.setGeometry(QtCore.QRect(0, 70, 241, 20))
        self.label_age.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.label_age.setAlignment(QtCore.Qt.AlignCenter)
        self.label_age.setObjectName("label_age")
        self.label_gender = QtWidgets.QLabel(self.frame_5)
        self.label_gender.setGeometry(QtCore.QRect(0, 100, 241, 20))
        self.label_gender.setStyleSheet("font-size: 20px;\n"
"color:white;")
        self.label_gender.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gender.setObjectName("label_gender")
        self.frame_6 = QtWidgets.QFrame(self.groupBox)
        self.frame_6.setGeometry(QtCore.QRect(640, 540, 241, 151))
        self.frame_6.setStyleSheet("border-radius: 20;\n"
"background-color: #F59100;\n"
"border: 0;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_min = QtWidgets.QLabel(self.frame_6)
        self.label_min.setGeometry(QtCore.QRect(0, 30, 241, 20))
        self.label_min.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.label_min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min.setObjectName("label_min")
        self.label_max = QtWidgets.QLabel(self.frame_6)
        self.label_max.setGeometry(QtCore.QRect(0, 60, 241, 20))
        self.label_max.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.label_max.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max.setObjectName("label_max")
        self.label_rate = QtWidgets.QLabel(self.frame_6)
        self.label_rate.setGeometry(QtCore.QRect(0, 90, 241, 20))
        self.label_rate.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.label_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rate.setObjectName("label_rate")
        self.frame_7 = QtWidgets.QFrame(self.groupBox)
        self.frame_7.setGeometry(QtCore.QRect(940, 540, 241, 151))
        self.frame_7.setStyleSheet("border-radius: 20;\n"
"background-color: #F59100;\n"
"border: 0;\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(0, 30, 241, 31))
        self.label_6.setStyleSheet("font-size: 20px;\n"
"color: rgb(35, 35, 35);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.saveButton = QtWidgets.QPushButton(self.frame_7)
        self.saveButton.setGeometry(QtCore.QRect(50, 70, 141, 41))
        self.saveButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"border-radius: 10;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E5E5E5;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.graphRightButton = QtWidgets.QPushButton(self.groupBox)
        self.graphRightButton.setGeometry(QtCore.QRect(300, 430, 70, 70))
        self.graphRightButton.setMinimumSize(QtCore.QSize(70, 70))
        self.graphRightButton.setMaximumSize(QtCore.QSize(70, 70))
        self.graphRightButton.setStyleSheet("background-color: #fff;\n"
"border-radius: 25;\n"
"border: 1px solid #F59100;\n"
"font-size: 40px;\n"
"")
        self.graphRightButton.setObjectName("graphRightButton")
        self.graphLeftButton = QtWidgets.QPushButton(self.groupBox)
        self.graphLeftButton.setGeometry(QtCore.QRect(160, 430, 70, 70))
        self.graphLeftButton.setMinimumSize(QtCore.QSize(70, 70))
        self.graphLeftButton.setMaximumSize(QtCore.QSize(70, 70))
        self.graphLeftButton.setStyleSheet("background-color: #fff;\n"
"border-radius: 25;\n"
"border: 1px solid #F59100;\n"
"font-size: 40px;\n"
"")
        self.graphLeftButton.setObjectName("graphLeftButton")
        self.stackedWidgetMain.addWidget(self.trackerPage)
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.groupBox_4 = QtWidgets.QGroupBox(self.loginPage)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 1231, 721))
        self.groupBox_4.setStyleSheet("border: none;\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.frame_8 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_8.setGeometry(QtCore.QRect(440, 140, 401, 341))
        self.frame_8.setStyleSheet("background-color: orange;\n"
"border-radius: 20px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(-40, 30, 471, 51))
        self.label_11.setStyleSheet("font-size: 40px; color: white;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.loginIdEdit = QtWidgets.QLineEdit(self.frame_8)
        self.loginIdEdit.setGeometry(QtCore.QRect(30, 140, 341, 41))
        self.loginIdEdit.setStyleSheet("background-color: #fff;\n"
"padding: 5px 10px;\n"
"")
        self.loginIdEdit.setText("")
        self.loginIdEdit.setObjectName("loginIdEdit")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(-40, 100, 471, 31))
        self.label_12.setStyleSheet("font-size: 22px;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.loginButton = QtWidgets.QPushButton(self.frame_8)
        self.loginButton.setGeometry(QtCore.QRect(100, 220, 201, 41))
        self.loginButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    font-size:18px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E5E5E5;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.toCreateButton = QtWidgets.QPushButton(self.frame_8)
        self.toCreateButton.setGeometry(QtCore.QRect(100, 270, 201, 41))
        self.toCreateButton.setStyleSheet("background-color: transparent;color: white;font-size:18px;")
        self.toCreateButton.setObjectName("toCreateButton")
        self.stackedWidgetMain.addWidget(self.loginPage)
        self.createPage = QtWidgets.QWidget()
        self.createPage.setObjectName("createPage")
        self.groupBox_3 = QtWidgets.QGroupBox(self.createPage)
        self.groupBox_3.setGeometry(QtCore.QRect(-1, -1, 1221, 711))
        self.groupBox_3.setStyleSheet("border: none;\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_3.setGeometry(QtCore.QRect(350, 50, 491, 611))
        self.frame_3.setStyleSheet("background-color: orange;\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 471, 51))
        self.label_2.setStyleSheet("font-size: 40px; color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.createIdEdit = QtWidgets.QLineEdit(self.frame_3)
        self.createIdEdit.setGeometry(QtCore.QRect(80, 150, 341, 41))
        self.createIdEdit.setStyleSheet("background-color: #fff;\n"
"padding: 5px 10px;\n"
"")
        self.createIdEdit.setText("")
        self.createIdEdit.setObjectName("createIdEdit")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 471, 31))
        self.label_7.setStyleSheet("font-size: 22px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 471, 31))
        self.label_8.setStyleSheet("font-size: 22px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.createNameEdit = QtWidgets.QLineEdit(self.frame_3)
        self.createNameEdit.setGeometry(QtCore.QRect(80, 250, 341, 41))
        self.createNameEdit.setStyleSheet("background-color: #fff;\n"
"padding: 5px 10px;\n"
"")
        self.createNameEdit.setText("")
        self.createNameEdit.setObjectName("createNameEdit")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(10, 310, 471, 31))
        self.label_9.setStyleSheet("font-size: 22px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.createAgeEdit = QtWidgets.QLineEdit(self.frame_3)
        self.createAgeEdit.setGeometry(QtCore.QRect(80, 350, 341, 41))
        self.createAgeEdit.setStyleSheet("background-color: #fff;\n"
"padding: 5px 10px;\n"
"")
        self.createAgeEdit.setText("")
        self.createAgeEdit.setObjectName("createAgeEdit")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(10, 410, 471, 31))
        self.label_10.setStyleSheet("font-size: 22px;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.comboGenderBox = QtWidgets.QComboBox(self.frame_3)
        self.comboGenderBox.setGeometry(QtCore.QRect(170, 450, 161, 31))
        self.comboGenderBox.setStyleSheet("background-color: white;")
        self.comboGenderBox.setObjectName("comboGenderBox")
        self.comboGenderBox.addItem("")
        self.comboGenderBox.addItem("")
        self.createButton = QtWidgets.QPushButton(self.frame_3)
        self.createButton.setGeometry(QtCore.QRect(150, 530, 201, 41))
        self.createButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    font-size:18px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E5E5E5;\n"
"}")
        self.createButton.setObjectName("createButton")
        self.stackedWidgetMain.addWidget(self.createPage)
        self.verticalLayout_7.addWidget(self.stackedWidgetMain)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.patientTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.patientTable.setGeometry(QtCore.QRect(190, 30, 861, 651))
        self.patientTable.setObjectName("patientTable")
        self.patientTable.setColumnCount(7)
        self.patientTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.patientTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.patientTable.setHorizontalHeaderItem(6, item)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout_2.addWidget(self.frame_pages, 0, 1, 1, 1)
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #F59100;\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #F59100;\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.frame_left_menu, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidgetMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", "SurfaceGating"))
        self.stopButton1.setText(_translate("MainWindow", "Stop"))
        self.startButton1.setText(_translate("MainWindow", "Start"))
        self.refreshButton.setText(_translate("MainWindow", "R"))
        self.label_name.setText(_translate("MainWindow", "Fauzan Valdera"))
        self.label_age.setText(_translate("MainWindow", "18 Years Old"))
        self.label_gender.setText(_translate("MainWindow", "Male"))
        self.label_min.setText(_translate("MainWindow", "Min : "))
        self.label_max.setText(_translate("MainWindow", "Max : "))
        self.label_rate.setText(_translate("MainWindow", "Rate : "))
        self.label_6.setText(_translate("MainWindow", "Save Patient"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.graphRightButton.setText(_translate("MainWindow", ">"))
        self.graphLeftButton.setText(_translate("MainWindow", "<"))
        self.label_11.setText(_translate("MainWindow", "LOGIN PATIENT"))
        self.label_12.setText(_translate("MainWindow", "Patient ID"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.toCreateButton.setText(_translate("MainWindow", "Create a patient"))
        self.label_2.setText(_translate("MainWindow", "CREATE PATIENT"))
        self.label_7.setText(_translate("MainWindow", "Patient ID"))
        self.label_8.setText(_translate("MainWindow", "Patient Name"))
        self.label_9.setText(_translate("MainWindow", "Patient Age"))
        self.label_10.setText(_translate("MainWindow", "Patient Gender"))
        self.comboGenderBox.setItemText(0, _translate("MainWindow", "Male"))
        self.comboGenderBox.setItemText(1, _translate("MainWindow", "Female"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        item = self.patientTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.patientTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.patientTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Age"))
        item = self.patientTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.patientTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Max"))
        item = self.patientTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Min"))
        item = self.patientTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rate"))
        self.btn_page_1.setText(_translate("MainWindow", "Tracker"))
        self.btn_page_2.setText(_translate("MainWindow", "Database"))
